"""Daemon identity checks for Virtuoso bridge sessions."""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

from virtuoso_bridge.models import ExecutionStatus


_TRUTHY = {"1", "true", "yes", "on"}


@dataclass(frozen=True)
class DaemonIdentity:
    user: str = ""
    home: str = ""
    pwd: str = ""
    workdir: str = ""
    cds_lib: str = ""
    profile: str = ""
    port: str = ""
    nonce: str = ""
    hostname: str = ""


@dataclass(frozen=True)
class IdentityCheck:
    identity: DaemonIdentity | None
    errors: tuple[str, ...] = ()
    warnings: tuple[str, ...] = ()

    @property
    def ok(self) -> bool:
        return not self.errors


def _profiled_env_key(base: str, profile: str | None) -> str:
    return f"{base}_{profile}" if profile else base


def identity_override_enabled(profile: str | None = None) -> bool:
    """Return True when cross-user/profile daemon identity checks are bypassed."""
    candidates = []
    if profile:
        candidates.append(_profiled_env_key("VB_ALLOW_DAEMON_IDENTITY_MISMATCH", profile))
    candidates.append("VB_ALLOW_DAEMON_IDENTITY_MISMATCH")
    for key in candidates:
        if os.getenv(key, "").strip().lower() in _TRUTHY:
            return True
    return False


def _clean_skill_output(value: str | None) -> str:
    text = (value or "").strip()
    if text.lower() == "nil":
        return ""
    if len(text) >= 2 and text[0] == '"' and text[-1] == '"':
        text = text[1:-1]
    return text.replace("\\n", "\n").replace('\\"', '"')


def _query(client: Any, expr: str, timeout: int) -> str:
    result = client.execute_skill(expr, timeout=timeout)
    if result.status != ExecutionStatus.SUCCESS:
        raise RuntimeError("; ".join(result.errors) or f"SKILL failed: {expr}")
    return _clean_skill_output(result.output)


def query_daemon_identity(client: Any, *, timeout: int = 5) -> DaemonIdentity:
    """Query the active Virtuoso session behind a reachable daemon."""
    return DaemonIdentity(
        user=_query(client, 'getShellEnvVar("USER")', timeout),
        home=_query(client, 'getShellEnvVar("HOME")', timeout),
        pwd=_query(client, 'getShellEnvVar("PWD")', timeout),
        workdir=_query(client, "getWorkingDir()", timeout),
        cds_lib=_query(client, 'getShellEnvVar("CDS_LIB")', timeout),
        profile=_query(client, 'getShellEnvVar("RB_PROFILE")', timeout),
        port=_query(client, 'getShellEnvVar("RB_PORT")', timeout),
        nonce=_query(client, 'getShellEnvVar("RB_DAEMON_NONCE")', timeout),
        hostname=_query(client, "getHostName()", timeout),
    )


def _expected_remote_port(profile: str | None, state: dict[str, Any] | None) -> str:
    if state and state.get("remote_port") is not None:
        return str(state["remote_port"])
    suffix = f"_{profile}" if profile else ""
    return os.getenv(f"VB_REMOTE_PORT{suffix}", "").strip()


def _expected_remote_user(profile: str | None, state: dict[str, Any] | None) -> str:
    if state and state.get("remote_user"):
        return str(state["remote_user"]).strip()
    suffix = f"_{profile}" if profile else ""
    return os.getenv(f"VB_REMOTE_USER{suffix}", "").strip()


def check_daemon_identity(
    identity: DaemonIdentity,
    *,
    profile: str | None,
    state: dict[str, Any] | None = None,
) -> IdentityCheck:
    """Compare daemon identity with the selected bridge profile/state."""
    if identity_override_enabled(profile):
        return IdentityCheck(identity=identity)

    errors: list[str] = []
    warnings: list[str] = []
    expected_user = _expected_remote_user(profile, state)
    expected_port = _expected_remote_port(profile, state)
    expected_profile = profile or ""
    expected_nonce = str(state.get("daemon_nonce", "")).strip() if state else ""

    if expected_user and identity.user and identity.user != expected_user:
        errors.append(
            f"daemon Unix user {identity.user!r} does not match tunnel user {expected_user!r}"
        )
    elif expected_user and not identity.user:
        warnings.append("daemon did not report Unix user")

    if expected_port and identity.port and identity.port != expected_port:
        errors.append(
            f"daemon port {identity.port!r} does not match profile remote port {expected_port!r}"
        )
    elif expected_port and not identity.port:
        warnings.append("daemon did not report RB_PORT")

    if expected_profile and identity.profile and identity.profile != expected_profile:
        errors.append(
            f"daemon profile {identity.profile!r} does not match selected profile {expected_profile!r}"
        )

    if expected_nonce and identity.nonce != expected_nonce:
        errors.append(
            "daemon nonce does not match the setup generated by the current bridge start"
        )

    return IdentityCheck(identity=identity, errors=tuple(errors), warnings=tuple(warnings))


def verify_daemon_identity(
    client: Any,
    *,
    profile: str | None,
    state: dict[str, Any] | None = None,
    timeout: int = 5,
) -> IdentityCheck:
    """Query and verify daemon identity. Raises only for unreachable daemons."""
    identity = query_daemon_identity(client, timeout=timeout)
    return check_daemon_identity(identity, profile=profile, state=state)
